/**
 * Which creatures have art for which way they are turned.
 *
 * GENERATED by `tools/genviews.py`. Do not edit by hand.
 *
 * It exists so the renderer never has to guess. Requesting a frame that was
 * not generated would be a 404, a 404 is a console error, and every harness
 * checks for console errors — so a speculative load would either break the
 * suite or force the suite to stop noticing real failures.
 *
 * A creature missing from this table simply always draws its front, which is
 * what the whole roster did before the frames existed.
 */
export type SpriteView = 'front' | 'back' | 'side' | 'attack';

export const VIEW_FRAMES: Record<string, readonly SpriteView[]> = {
  f1_boss: ['attack', 'back', 'side'],
  f1_enemy_ink: ['attack', 'back', 'side'],
  f1_enemy_moth: ['attack', 'back', 'side'],
  f1_enemy_wraith: ['attack', 'back', 'side'],
  f2_boss: ['attack', 'back', 'side'],
  f2_enemy_cleaver: ['attack', 'back', 'side'],
  f2_enemy_hound: ['attack', 'back', 'side'],
  f2_enemy_imp: ['attack', 'back', 'side'],
  f3_boss: ['attack', 'back', 'side'],
  f3_enemy_creeper: ['attack', 'back', 'side'],
  f3_enemy_hulk: ['attack', 'back', 'side'],
  f3_enemy_priest: ['attack', 'back', 'side'],
  f4_boss: ['attack', 'back', 'side'],
  f4_enemy_bellows: ['attack', 'back', 'side'],
  f4_enemy_slag: ['attack', 'back', 'side'],
  f4_enemy_wasp: ['attack', 'back', 'side'],
  f5_boss: ['attack', 'back', 'side'],
  f5_enemy_acolyte: ['attack', 'back', 'side'],
  f5_enemy_husk: ['attack', 'back', 'side'],
  f5_enemy_sentinel: ['attack', 'back', 'side'],
};

/** The frames shipped for one creature, front always included. */
export function viewsFor(id: string): readonly SpriteView[] {
  return VIEW_FRAMES[id] ?? [];
}
