#!/usr/bin/env python3
"""
Back, side and attack frames for every hostile.

    tools/genviews.py                     # the back+side turnaround, two per image
    tools/genviews.py --attack            # the single-panel attack pose
    tools/genviews.py --only f1_boss
    tools/genviews.py --split-only        # re-split cached sheets, no API calls
    tools/genviews.py --attack --refresh  # throw the cached sheets away and redo

The two runs are separate on purpose. The turnaround's whole instruction is "the same
creature standing still, TURNED"; the attack's is "the same creature MID-STRIKE".
Asking one image for two calm views plus a lunge returned three lunges.

Why it works this way:

**One image, two views.** A back and a profile of the same creature come out of a
single generation asking for them side by side, which halves the run — twenty calls
for forty frames. The panels are then cut apart on their alpha, not at the
half-way mark, because the model does not centre them and a creature clipped down
its spine is worse than no back at all.

**Generated by REFERENCE, never by prompt alone.** Pixel_Resolution_Steps
established at the cost of six wasted generations that a changed prompt returns a
changed DESIGN — the floor-1 boss came back as a winged figure instead of an open
book with an eye. A back view from a prompt would be a different creature seen from
behind, which is worse than useless: it would look like a different enemy. The
existing raw goes in as the reference and the prompt only says which way to turn.

**1K, which is the floor.** The API offers 1K, 2K and 4K, and even 1K is thrown
away almost entirely — the largest frame that ships is 190px tall, so a 1254px
generation is already about 60x more pixels than survive. There is nothing to gain
above the minimum.

**Matted before splitting.** One background-removal call per SHEET rather than one
per panel, so the alpha that defines the panels is the same alpha that ships. It
also means the split is a gap in coverage rather than a guess about whiteness, and
enclosed background — the gap between a hound's legs — is handled for the new
frames the same way `genart.matted()` handles it for the fronts.

**Height is inherited from the front.** A creature is the same height whichever way
it is turned, so every view is resampled to the front's height at that step and its
width follows its own silhouette. Sizing each view independently would make
creatures grow and shrink as they turned.

Left and right are the same drawing: only ONE profile is generated, and the renderer
mirrors it. See the phase doc.
"""
from __future__ import annotations

import argparse
import importlib.util
import json
import os
import subprocess
import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
spec = importlib.util.spec_from_file_location("genart", ROOT / "tools" / "genart.py")
G = importlib.util.module_from_spec(spec)
spec.loader.exec_module(G)

SHEET_DIR = G.RAW_DIR / "views"
NOBG_DIR = SHEET_DIR / "nobg"
ASSET_CREATOR = G.ASSET_CREATOR

# The two panels, in the order the prompt asks for them.
VIEWS = ("back", "side")

# The attack pose is its own single-panel run, and the pose itself comes from the
# MANIFEST — one bespoke line per creature, in `attack`.
#
# It used to be one generic string for all twenty, and that was wrong in a way worth
# recording. It read "weapon or claws or jaws thrown forward ... mouth open if it has
# one", which is a shopping list, and a model handed a shopping list fills it: every
# creature came back with a hand thrust forward, including the ones with no hands, and
# the floating grimoire grew a fanged mouth and a clawed arm to comply. Twenty
# creatures got one pose and several got anatomy they do not have.
#
# So the prompt now says only what THIS creature does with the body it has, and
# forbids invention explicitly. A moth attacks by flaring its flame, a bone hound by
# pouncing, a bellows fiend by crushing its own torso, the grimoire by firing light
# from between its pages. No two are the same verb.
ATTACK_FRAME = (
    "ONE view of the EXACT SAME CREATURE as the reference image, on a plain solid "
    "white background. Match the reference exactly: same design, same colours, same "
    "proportions, same ANATOMY. "
    "CRITICAL: do not add, invent or grow any body part the reference does not "
    "already have — no extra arms, hands, claws, limbs, mouths, teeth, faces or eyes. "
    "If it has no hands it does not reach; if it has no mouth it does not bite. "
    "It is ATTACKING, caught at the peak of the action: {attack}. "
    "Violent, committed, mid-motion. Front-facing, full body, centered, with a small "
    "margin of empty space at every edge. " + G.STYLE + "."
)


def attack_prompt(asset: dict) -> str | None:
    """The bespoke attack line for one creature, or None if it has not been written."""
    a = asset.get("attack")
    return ATTACK_FRAME.format(attack=a.strip()) if a else None


def hostiles(assets: list[dict]) -> list[dict]:
    """Enemies and bosses. Golems and scenery are a follow-up, see the phase doc."""
    return [a for a in assets if "_enemy_" in a["id"] or a["id"].endswith("_boss")]


def run(cmd: list[str], env: dict[str, str]) -> bool:
    res = subprocess.run(cmd, capture_output=True, text=True, env=env)
    if res.returncode != 0:
        print(f"      {res.stderr.strip()[:200]}", flush=True)
    return res.returncode == 0


def make_sheet(asset: dict, env: dict[str, str], attack: bool = False) -> Path | None:
    """Generate the sheet for one creature, cached."""
    out = (SHEET_DIR / "attack" if attack else SHEET_DIR) / f"{asset['id']}.png"
    if out.exists():
        return out
    ref = G.raw_path(asset["id"])
    if not ref.exists():
        print(f"  [skip] {asset['id']} (no front raw to reference)")
        return None
    if attack and not attack_prompt(asset):
        print(f"  [skip] {asset['id']} (no `attack` line in the manifest)")
        return None
    out.parent.mkdir(parents=True, exist_ok=True)
    ok = run([
        "uvx", "--from", str(ASSET_CREATOR), "asset-creator",
        "--prompt", attack_prompt(asset) if attack else PROMPT,
        "--reference", str(ref),
        # Wide when two views sit side by side, square for a single pose. 1K is the
        # lowest the API offers and far more than survives the resample.
        "--aspect", "1:1" if attack else "16:9",
        "--resolution", "1K",
        "--seed", str(asset.get("seed", 1234) + (9100 if attack else 7000)),
        "--output", str(out),
    ], env)
    if not ok or not out.exists():
        print(f"  [FAIL gen] {asset['id']}")
        return None
    return out


def matte_sheet(sheet: Path, env: dict[str, str]) -> Path | None:
    """One background-removal call per sheet, cached."""
    out = sheet.parent / "nobg" / sheet.name
    if out.exists():
        return out
    out.parent.mkdir(parents=True, exist_ok=True)
    ok = run([
        "uvx", "--from", str(ASSET_CREATOR), "asset-creator",
        "--remove-bg", "--reference", str(sheet), "--output", str(out),
    ], env)
    if not ok or not out.exists():
        print(f"  [FAIL bg] {sheet.stem}")
        return None
    return out


def split_panels(img: Image.Image, want: int = 2) -> list[Image.Image]:
    """
    Cut a sheet into its subjects on columns that carry no coverage.

    A gap has to be WIDE to count. A creature with an outstretched arm or a tail
    has thin columns inside its own silhouette, and treating any empty column as a
    boundary shatters one creature into five. The threshold is a fraction of the
    sheet width, which is scale-free.

    Returns the `want` widest runs, left to right, or fewer if the sheet did not
    separate — the caller reports that rather than shipping a creature cut in half.
    """
    img = img.convert("RGBA")
    w, h = img.size
    a = img.getchannel("A")
    # Coverage per column.
    cols = [0] * w
    px = a.load()
    for x in range(w):
        n = 0
        for y in range(0, h, 2):          # every other row is plenty and 2x faster
            if px[x, y] > 40:
                n += 1
        cols[x] = n

    def split_at(min_gap: int) -> list[tuple[int, int]]:
        runs: list[tuple[int, int]] = []
        start = None
        gap = 0
        for x in range(w):
            if cols[x] > 0:
                if start is None:
                    start = x
                gap = 0
            elif start is not None:
                gap += 1
                if gap >= min_gap:
                    runs.append((start, x - gap + 1))
                    start = None
                    gap = 0
        if start is not None:
            runs.append((start, w))
        # Drop specks: narrower than a twentieth of the sheet is not a subject.
        return [r for r in runs if r[1] - r[0] >= w * 0.05]

    # Start strict and RELAX until the sheet yields the number of subjects asked
    # for. One fixed threshold cannot serve both failure modes: too small and a
    # creature with an outstretched arm shatters into pieces, too large and two
    # subjects standing close merge into one. The floor-3 creeper's two views were
    # separated by four columns out of 1536 — a quarter of one percent — where a
    # tenth of that gap would have cut other creatures in half.
    strict = max(4, int(w * 0.02))
    for min_gap in range(strict, 1, -1):
        runs = split_at(min_gap)
        if len(runs) == want:
            return [img.crop((x0, 0, x1, h)) for x0, x1 in sorted(runs)]

    # Never separated, or never stopped. Hand back the strict answer so the caller
    # refuses it: a creature cut down its spine is worse than no back at all.
    return [img.crop((x0, 0, x1, h)) for x0, x1 in sorted(split_at(strict))]


def post_view(front_id: str, view: str, panel: Image.Image) -> dict[int, tuple[int, int]]:
    """
    Write one view at every shipped density, at the FRONT's height.

    Width is left to the silhouette: a profile is narrower than a front and forcing
    it to the front's width would squash it. Height is inherited so a creature does
    not change size when it turns.
    """
    sizes: dict[int, tuple[int, int]] = {}
    front = G.OUT_DIR / f"{front_id}.png"
    with Image.open(front) as f:
        _, h144 = f.size

    panel = G.crop_to_content(panel)
    for step, tune in G.STEP_TUNE.items():
        if step != 144 and not G.step_dir(step).exists():
            continue                              # a roster that was cut, e.g. 18
        fh = max(3, round(h144 * step / 144))
        img = G.punch(panel, tune["contrast"])
        img = G.to_pixel_grid(img, fh - 2, tune["colors"],
                              median=True, sharpen=tune["sharpen"])
        img = G.add_keyline(img)
        out = G.step_dir(step)
        out.mkdir(parents=True, exist_ok=True)
        img.save(out / f"{front_id}_{view}.png", optimize=True)
        sizes[step] = img.size
    return sizes


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", help="comma-separated asset ids")
    ap.add_argument("--split-only", action="store_true",
                    help="re-split and re-post cached sheets; no API calls")
    ap.add_argument("--attack", action="store_true",
                    help="the single-panel attack pose run instead of the turnaround")
    ap.add_argument("--refresh", action="store_true",
                    help="discard cached sheets for the selected run and generate again")
    args = ap.parse_args()

    assets = [a for a in json.loads(G.MANIFEST.read_text())["assets"] if "id" in a]
    todo = hostiles(assets)
    if args.only:
        want = {s.strip() for s in args.only.split(",")}
        todo = [a for a in todo if a["id"] in want]
    if not todo:
        sys.exit("no hostiles selected")

    env = os.environ.copy() if args.split_only else G.load_keys()
    views = ("attack",) if args.attack else VIEWS
    print(f"{len(todo)} hostiles, {len(views)} view(s) each")

    bad: list[str] = []
    for a in todo:
        aid = a["id"]
        if args.split_only:
            base = (SHEET_DIR / "attack" if args.attack else SHEET_DIR) / "nobg"
            sheet = base / f"{aid}.png"
            if not sheet.exists():
                print(f"  [skip] {aid} (no matted sheet)")
                continue
        else:
            if args.refresh:
                base = SHEET_DIR / "attack" if args.attack else SHEET_DIR
                for stale in (base / f"{aid}.png", base / "nobg" / f"{aid}.png"):
                    stale.unlink(missing_ok=True)
            raw = make_sheet(a, env, args.attack)
            if not raw:
                bad.append(aid)
                continue
            sheet = matte_sheet(raw, env)
            if not sheet:
                bad.append(aid)
                continue

        with Image.open(sheet) as im:
            panels = split_panels(im, len(views))
        if len(panels) != len(views):
            print(f"  [FAIL split] {aid} — found {len(panels)} subject(s), wanted {len(views)}")
            bad.append(aid)
            continue

        out = []
        for view, panel in zip(views, panels):
            sizes = post_view(aid, view, panel)
            out.append(f"{view} {sizes.get(144, ('?', '?'))[0]}x{sizes.get(144, ('?', '?'))[1]}")
        print(f"  [pix] {aid} -> {', '.join(out)}", flush=True)

    write_index()
    if bad:
        print(f"\n{len(bad)} need another look: {', '.join(bad)}")


INDEX = ROOT / "src" / "art" / "views.ts"


def write_index() -> None:
    """
    Emit which view frames actually exist, as TypeScript.

    The renderer must never guess. Asking for `<id>_back.png` and handling the 404
    would work, but a failed fetch is a console error, and "no page errors" is a
    check in every harness — so a speculative load would either break the suite or
    force the suite to start ignoring real errors. Generated from the filesystem so
    it cannot drift from the art.
    """
    found: dict[str, list[str]] = {}
    for f in sorted(G.OUT_DIR.glob("*.png")):
        for view in (*VIEWS, "attack"):
            if f.stem.endswith(f"_{view}"):
                found.setdefault(f.stem[: -len(view) - 1], []).append(view)
    rows = "\n".join(
        f"  {k}: [{', '.join(repr(v).replace(chr(39), chr(39)) for v in sorted(vs))}],"
        for k, vs in sorted(found.items())
    )
    INDEX.write_text(
        "/**\n"
        " * Which creatures have art for which way they are turned.\n"
        " *\n"
        " * GENERATED by `tools/genviews.py`. Do not edit by hand.\n"
        " *\n"
        " * It exists so the renderer never has to guess. Requesting a frame that was\n"
        " * not generated would be a 404, a 404 is a console error, and every harness\n"
        " * checks for console errors — so a speculative load would either break the\n"
        " * suite or force the suite to stop noticing real failures.\n"
        " *\n"
        " * A creature missing from this table simply always draws its front, which is\n"
        " * what the whole roster did before the frames existed.\n"
        " */\n"
        "export type SpriteView = 'front' | 'back' | 'side' | 'attack';\n\n"
        "export const VIEW_FRAMES: Record<string, readonly SpriteView[]> = {\n"
        f"{rows}\n"
        "};\n\n"
        "/** The frames shipped for one creature, front always included. */\n"
        "export function viewsFor(id: string): readonly SpriteView[] {\n"
        "  return VIEW_FRAMES[id] ?? [];\n"
        "}\n"
    )
    print(f"  [idx] {INDEX.relative_to(ROOT)} — {len(found)} creature(s)")


if __name__ == "__main__":
    main()
