#!/usr/bin/env python3
"""
Back and side frames for every hostile, two views per generation.

    tools/genviews.py                  # everything missing
    tools/genviews.py --only f1_boss
    tools/genviews.py --split-only     # re-split and re-post cached sheets, no API

Why it works this way:

**One image, two views.** A back and a profile of the same creature come out of a
single generation asking for them side by side, which halves the run — twenty calls
for forty frames. The panels are then cut apart on their alpha, not at the
half-way mark, because the model does not centre them and a creature clipped down
its spine is worse than no back at all.

**Generated by REFERENCE, never by prompt alone.** Pixel_Resolution_Steps
established at the cost of six wasted generations that a changed prompt returns a
changed DESIGN — the floor-1 boss came back as a winged figure instead of an open
book with an eye. A back view from a prompt would be a different creature seen from
behind, which is worse than useless: it would look like a different enemy. The
existing raw goes in as the reference and the prompt only says which way to turn.

**1K, which is the floor.** The API offers 1K, 2K and 4K, and even 1K is thrown
away almost entirely — the largest frame that ships is 190px tall, so a 1254px
generation is already about 60x more pixels than survive. There is nothing to gain
above the minimum.

**Matted before splitting.** One background-removal call per SHEET rather than one
per panel, so the alpha that defines the panels is the same alpha that ships. It
also means the split is a gap in coverage rather than a guess about whiteness, and
enclosed background — the gap between a hound's legs — is handled for the new
frames the same way `genart.matted()` handles it for the fronts.

**Height is inherited from the front.** A creature is the same height whichever way
it is turned, so every view is resampled to the front's height at that step and its
width follows its own silhouette. Sizing each view independently would make
creatures grow and shrink as they turned.

Left and right are the same drawing: only ONE profile is generated, and the renderer
mirrors it. See the phase doc.
"""
from __future__ import annotations

import argparse
import importlib.util
import json
import os
import subprocess
import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
spec = importlib.util.spec_from_file_location("genart", ROOT / "tools" / "genart.py")
G = importlib.util.module_from_spec(spec)
spec.loader.exec_module(G)

SHEET_DIR = G.RAW_DIR / "views"
NOBG_DIR = SHEET_DIR / "nobg"
ASSET_CREATOR = G.ASSET_CREATOR

# The two panels, in the order the prompt asks for them.
VIEWS = ("back", "side")

PROMPT = (
    "TWO VIEWS OF THE EXACT SAME CREATURE, side by side, on a plain solid white "
    "background, with a clear empty gap between them. Match the reference image "
    "exactly: same design, same colours, same proportions, same silhouette, same "
    "size. This is a turnaround sheet of one character, not two characters. "
    "LEFT VIEW: the creature seen from DIRECTLY BEHIND — its back to the viewer, "
    "the back of its head and body, no face visible at all. "
    "RIGHT VIEW: the creature seen from the SIDE in exact profile, facing to the "
    "right, one side of the body toward the viewer. "
    "Both views full body from head to feet, standing at the same height, upright, "
    "level with each other. " + G.STYLE + "."
)


def hostiles(assets: list[dict]) -> list[dict]:
    """Enemies and bosses. Golems and scenery are a follow-up, see the phase doc."""
    return [a for a in assets if "_enemy_" in a["id"] or a["id"].endswith("_boss")]


def run(cmd: list[str], env: dict[str, str]) -> bool:
    res = subprocess.run(cmd, capture_output=True, text=True, env=env)
    if res.returncode != 0:
        print(f"      {res.stderr.strip()[:200]}", flush=True)
    return res.returncode == 0


def make_sheet(asset: dict, env: dict[str, str]) -> Path | None:
    """Generate the two-view sheet for one creature, cached."""
    out = SHEET_DIR / f"{asset['id']}.png"
    if out.exists():
        return out
    ref = G.raw_path(asset["id"])
    if not ref.exists():
        print(f"  [skip] {asset['id']} (no front raw to reference)")
        return None
    out.parent.mkdir(parents=True, exist_ok=True)
    ok = run([
        "uvx", "--from", str(ASSET_CREATOR), "asset-creator",
        "--prompt", PROMPT,
        "--reference", str(ref),
        # Wide, because the two views sit side by side. 1K is the lowest the API
        # offers and far more than survives the resample.
        "--aspect", "16:9",
        "--resolution", "1K",
        "--seed", str(asset.get("seed", 1234) + 7000),
        "--output", str(out),
    ], env)
    if not ok or not out.exists():
        print(f"  [FAIL gen] {asset['id']}")
        return None
    return out


def matte_sheet(sheet: Path, env: dict[str, str]) -> Path | None:
    """One background-removal call per sheet, cached."""
    out = NOBG_DIR / sheet.name
    if out.exists():
        return out
    out.parent.mkdir(parents=True, exist_ok=True)
    ok = run([
        "uvx", "--from", str(ASSET_CREATOR), "asset-creator",
        "--remove-bg", "--reference", str(sheet), "--output", str(out),
    ], env)
    if not ok or not out.exists():
        print(f"  [FAIL bg] {sheet.stem}")
        return None
    return out


def split_panels(img: Image.Image, want: int = 2) -> list[Image.Image]:
    """
    Cut a sheet into its subjects on columns that carry no coverage.

    A gap has to be WIDE to count. A creature with an outstretched arm or a tail
    has thin columns inside its own silhouette, and treating any empty column as a
    boundary shatters one creature into five. The threshold is a fraction of the
    sheet width, which is scale-free.

    Returns the `want` widest runs, left to right, or fewer if the sheet did not
    separate — the caller reports that rather than shipping a creature cut in half.
    """
    img = img.convert("RGBA")
    w, h = img.size
    a = img.getchannel("A")
    # Coverage per column.
    cols = [0] * w
    px = a.load()
    for x in range(w):
        n = 0
        for y in range(0, h, 2):          # every other row is plenty and 2x faster
            if px[x, y] > 40:
                n += 1
        cols[x] = n

    def split_at(min_gap: int) -> list[tuple[int, int]]:
        runs: list[tuple[int, int]] = []
        start = None
        gap = 0
        for x in range(w):
            if cols[x] > 0:
                if start is None:
                    start = x
                gap = 0
            elif start is not None:
                gap += 1
                if gap >= min_gap:
                    runs.append((start, x - gap + 1))
                    start = None
                    gap = 0
        if start is not None:
            runs.append((start, w))
        # Drop specks: narrower than a twentieth of the sheet is not a subject.
        return [r for r in runs if r[1] - r[0] >= w * 0.05]

    # Start strict and RELAX until the sheet yields the number of subjects asked
    # for. One fixed threshold cannot serve both failure modes: too small and a
    # creature with an outstretched arm shatters into pieces, too large and two
    # subjects standing close merge into one. The floor-3 creeper's two views were
    # separated by four columns out of 1536 — a quarter of one percent — where a
    # tenth of that gap would have cut other creatures in half.
    strict = max(4, int(w * 0.02))
    for min_gap in range(strict, 1, -1):
        runs = split_at(min_gap)
        if len(runs) == want:
            return [img.crop((x0, 0, x1, h)) for x0, x1 in sorted(runs)]

    # Never separated, or never stopped. Hand back the strict answer so the caller
    # refuses it: a creature cut down its spine is worse than no back at all.
    return [img.crop((x0, 0, x1, h)) for x0, x1 in sorted(split_at(strict))]


def post_view(front_id: str, view: str, panel: Image.Image) -> dict[int, tuple[int, int]]:
    """
    Write one view at every shipped density, at the FRONT's height.

    Width is left to the silhouette: a profile is narrower than a front and forcing
    it to the front's width would squash it. Height is inherited so a creature does
    not change size when it turns.
    """
    sizes: dict[int, tuple[int, int]] = {}
    front = G.OUT_DIR / f"{front_id}.png"
    with Image.open(front) as f:
        _, h144 = f.size

    panel = G.crop_to_content(panel)
    for step, tune in G.STEP_TUNE.items():
        if step != 144 and not G.step_dir(step).exists():
            continue                              # a roster that was cut, e.g. 18
        fh = max(3, round(h144 * step / 144))
        img = G.punch(panel, tune["contrast"])
        img = G.to_pixel_grid(img, fh - 2, tune["colors"],
                              median=True, sharpen=tune["sharpen"])
        img = G.add_keyline(img)
        out = G.step_dir(step)
        out.mkdir(parents=True, exist_ok=True)
        img.save(out / f"{front_id}_{view}.png", optimize=True)
        sizes[step] = img.size
    return sizes


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", help="comma-separated asset ids")
    ap.add_argument("--split-only", action="store_true",
                    help="re-split and re-post cached sheets; no API calls")
    args = ap.parse_args()

    assets = [a for a in json.loads(G.MANIFEST.read_text())["assets"] if "id" in a]
    todo = hostiles(assets)
    if args.only:
        want = {s.strip() for s in args.only.split(",")}
        todo = [a for a in todo if a["id"] in want]
    if not todo:
        sys.exit("no hostiles selected")

    env = os.environ.copy() if args.split_only else G.load_keys()
    print(f"{len(todo)} hostiles, {len(VIEWS)} views each")

    bad: list[str] = []
    for a in todo:
        aid = a["id"]
        if args.split_only:
            sheet = NOBG_DIR / f"{aid}.png"
            if not sheet.exists():
                print(f"  [skip] {aid} (no matted sheet)")
                continue
        else:
            raw = make_sheet(a, env)
            if not raw:
                bad.append(aid)
                continue
            sheet = matte_sheet(raw, env)
            if not sheet:
                bad.append(aid)
                continue

        with Image.open(sheet) as im:
            panels = split_panels(im, len(VIEWS))
        if len(panels) != len(VIEWS):
            print(f"  [FAIL split] {aid} — found {len(panels)} subject(s), wanted {len(VIEWS)}")
            bad.append(aid)
            continue

        out = []
        for view, panel in zip(VIEWS, panels):
            sizes = post_view(aid, view, panel)
            out.append(f"{view} {sizes.get(144, ('?', '?'))[0]}x{sizes.get(144, ('?', '?'))[1]}")
        print(f"  [pix] {aid} -> {', '.join(out)}", flush=True)

    write_index()
    if bad:
        print(f"\n{len(bad)} need another look: {', '.join(bad)}")


INDEX = ROOT / "src" / "art" / "views.ts"


def write_index() -> None:
    """
    Emit which view frames actually exist, as TypeScript.

    The renderer must never guess. Asking for `<id>_back.png` and handling the 404
    would work, but a failed fetch is a console error, and "no page errors" is a
    check in every harness — so a speculative load would either break the suite or
    force the suite to start ignoring real errors. Generated from the filesystem so
    it cannot drift from the art.
    """
    found: dict[str, list[str]] = {}
    for f in sorted(G.OUT_DIR.glob("*.png")):
        for view in VIEWS:
            if f.stem.endswith(f"_{view}"):
                found.setdefault(f.stem[: -len(view) - 1], []).append(view)
    rows = "\n".join(
        f"  {k}: [{', '.join(repr(v).replace(chr(39), chr(39)) for v in sorted(vs))}],"
        for k, vs in sorted(found.items())
    )
    INDEX.write_text(
        "/**\n"
        " * Which creatures have art for which way they are turned.\n"
        " *\n"
        " * GENERATED by `tools/genviews.py`. Do not edit by hand.\n"
        " *\n"
        " * It exists so the renderer never has to guess. Requesting a frame that was\n"
        " * not generated would be a 404, a 404 is a console error, and every harness\n"
        " * checks for console errors — so a speculative load would either break the\n"
        " * suite or force the suite to stop noticing real failures.\n"
        " *\n"
        " * A creature missing from this table simply always draws its front, which is\n"
        " * what the whole roster did before the frames existed.\n"
        " */\n"
        "export type SpriteView = 'front' | 'back' | 'side';\n\n"
        "export const VIEW_FRAMES: Record<string, readonly SpriteView[]> = {\n"
        f"{rows}\n"
        "};\n\n"
        "/** The frames shipped for one creature, front always included. */\n"
        "export function viewsFor(id: string): readonly SpriteView[] {\n"
        "  return VIEW_FRAMES[id] ?? [];\n"
        "}\n"
    )
    print(f"  [idx] {INDEX.relative_to(ROOT)} — {len(found)} creature(s)")


if __name__ == "__main__":
    main()
